### ISSUE TITLE
adding a new column for supports showing the percentage of use of a given buffing skill

### ISSUE THREAD

**Issue by noname483** [snoww/loa-logs#129]
Hello, is it possible to add a column showing the actual percentage of use of a given buffing skill? I want the program to show the percentage of use of the buffing skill throughout the fight. When playing as a support, it starts to annoy me that dps players don't look at their mistakes but see the problem with supports and their uptime. For example, I can be god support and have 100% uptime, but the program will show that the dps player was buffed only 50% of the time because he was licking the ground for half the game or did nothing because he was trying to avoid the boss mechanic and did not do dps. This is perfectly demonstrated by the example on this screenshot. The difference between the players, one player had 64.1% uptime buff, the other 45% So what is the actual support uptime? Since the program shows such values ​​​​and the players do not understand them and are toxic towards supports and blame them for everything without seeing the problem with themselves.
![Nowy obraz mapy bitowej](https://github.com/user-attachments/assets/fa04e766-5623-4616-a153-b097ab736d84)

**Comment by snoww** [comment]
i have no idea what you are asking for. the percentage here is the damage done while ur buff is up. if youre buffing when no one is doing damage, the percentage wont go up. if you buff when everyone is doing damage, or if your buff is always up, the percentage will become higher.

if you are a god support and have 100% uptime, the columns will show 100%, because every time your party members does damage, they have buffs. 

if your party members are on the ground, they are not doing damage, thus the percentage will not change regardless if you're buffing or not.

the difference in percentage could be that they did a big burst during your buff downtime, thus appearing lower, which is correct because most of their damage was not buffed.
